const carouselItemsData = [
  {
    title: "Items to explore",
    items: [
      "https://m.media-amazon.com/images/I/51nISmynRoL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61fwdAwoukL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71L7FGU3LiL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61fOBcp6weL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/41Spb6KMsqL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/51d+BTHV3RL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/51egBMPUW8L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/91Yj17xk+eL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61WVy61nGiL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61xAjSS+7SL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61xo-AIv5JL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/51sGXnCu8gL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61Z3xWUnkqL._AC_SY400_.jpg",
    ],
  },
  {
    title: "More items to consider",
    items: [
      "https://m.media-amazon.com/images/I/71o8Q5XJS5L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61+btxzpfDL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/7120GgUKj3L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81fSoQd7nsL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61+fe8F-vmL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71+OQysjHnL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71d225Tb41L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81+qUMLeNML._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71NVQWmax1L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/51JbsHSktkL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61UzY7vPUIL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71oayBSFUYL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61WFNqf8hVL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/51sCVB0IZDL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61+WYAjltpL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71iXGWXM56L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71oayBSFUYL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71eGsUPZm2L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71bhWgQK-cL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61ZRU9gnbxL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/41ijQEHFicS._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/6187mqYfstL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61-jovn4Y+L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71iH3zFwXXL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61fU3njgzZL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61tZb1KHNYL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/51rN+9wKZoL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71IrGw7RMAS._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61HpJ9w4m9L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71bXxtAvtEL._AC_SY400_.jpg",
    ],
    link: "#",
    linkPlaceholder: "See more",
  },
  {
    title: "Best Sellers in Books",
    items: [
      "https://m.media-amazon.com/images/I/61m1Vxw8tiL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71Mx-bE91+L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71Yikzkkk4L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71FFo6kU5NL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71j25Ib5FSL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71l9pCV99FL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61tqfa+xbWL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/617uZq23IPL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/613KCs7szvL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71nCY2F3UKL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81tJMFwH-uL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81wgcld4wxL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81ZylhG5VnL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81RuWvOhRPL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81sSQixvtBL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61xkvfPVupL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81T-PQ9HFTL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71aG+xDKSYL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81HA6TJ5K-L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81hHy5XrdKL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/91cqEsyjd-L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81Ekpv7AwKL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71gDtm1U0FL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71ow6v8lfQL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71ZVzeVj1RL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61Bdp7XZhDL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81WXGS76dzL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/51kcX5PpaZL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/811SRapU9aL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/612V9dt-NGS._AC_SY400_.jpg",
    ],
  },
  {
    title: "Inspired by your shopping trends",
    items: [
      "https://m.media-amazon.com/images/I/71eVjWy8QAL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/616XeJN-YrL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71r7vu0VveL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/41q6IqILB0L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61FnGpseS3L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81-C7lGtQsL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81S9p8XXYDL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/51LN7O6k2GS._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71icTLikAeL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61U8XXJ05pL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61STkRIYJAL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61UO6uvSbAL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81e6dYDfU4L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61oaGJnwNFL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/91PuSthnhhL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71J0iPYw2YL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61WsLIAGDgL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71eXIA8sytL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/51P5WGxMzeL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/51PxlJEGaOL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/51DBX1rqeLS._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81dB7KtNPZS._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/51gx-K+YD+L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71BNzekVAXL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/712c0-kY8PL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81rg-38AdJL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61gSV1Jta5L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/91S1PIX+yWL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61InEiZX+ZL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71++hj67xeL._AC_SY400_.jpg",
    ],
  },
  {
    title: "Best Sellers in Cell Phones & Accessories",
    items: [
      "https://m.media-amazon.com/images/I/81MZ5D1wHpL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71ncIkBW8qL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71OicfvCsbL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71iaXGldcsL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/8100ifwmXwL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71ynOeDnVFL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71yj-42DunL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/619Dkv7++NL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/719+wCOFNNL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81CVqvi2wIL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71eUx6WUpNL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61UM-8FgMuS._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61xnJ50VroL._AC_SY400_.jpg",
    ],
  },
  {
    title: "Buy in other parts of the store",
    items: [
      "https://m.media-amazon.com/images/I/71XG7AeZA1L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71g8espOgeL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/612j2V8iucL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/51YE7O4bM+L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/717ubYggVJL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81lqn0l2cPL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61ZJVFqSJoL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71gJ9U0bVWL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/41iVXz-vtgL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61SrjFuOjVL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71t7UWrIxZL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71fpBFzVBSL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71ljjF6RA1L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71J6ZRogjML._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71WY0EFGKBL._AC_SY400_.jpg",
    ],
  },
  {
    title: "Related to items you've viewed",
    items: [
      "https://m.media-amazon.com/images/I/71HAM56AEGL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71gYXnMZXoL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/611hYEemnyL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71D0naxZ8RL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/21+2gXvpcCL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71PHKPH4NQL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/51X3EhdcbPL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71i49M4hv2L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71jG+e7roXL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61Fp3BqziNL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61lPH+TNpSL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/61J6yUeJ0cL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81RCOr3hJOL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71IyteItZhL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/81k1vbjjv5L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/71sOrI1hB9L._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/815uX7wkOZS._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/610AomjKVwL._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/818vEGdvS+S._AC_SY400_.jpg",
      "https://m.media-amazon.com/images/I/716NEN4UVXL._AC_SY400_.jpg",
    ],
    link: "#",
    linkPlaceholder: "See more",
  },
];

export default carouselItemsData;
