const subMenus = [
  {
    header: "Digital Content & Devices",
    name: "Amazon Music",
    sections: [
      {
        title: "Stream Music",
        items: [
          { name: "Amazon Music Unlimited", link: "#" },
          { name: "Free Streaming Music", link: "#" },
          { name: "Podcasts", link: "#" },
          { name: "Open Web Player", link: "#" },
          { name: "Download the app", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Digital Content & Devices",
    name: "Kindle E-readers & Books",
    sections: [
      {
        title: "Kindle E-Readers",
        items: [
          { name: "Kindle Kids", link: "#" },
          { name: "Kindle", link: "#" },
          { name: "Kindle Paperwhite", link: "#" },
          { name: "Kindle Oasis", link: "#" },
          { name: "Kindle Accessories", link: "#" },
          { name: "See all Kindle E-Readers", link: "#" },
        ],
      },
      {
        title: "Kindle Store",

        items: [
          { name: "Kindle Books", link: "#" },
          { name: "Kindle Unlimited", link: "#" },
          { name: "Prime Reading", link: "#" },
          { name: "Kindle Vella", link: "#" },
        ],
      },
      {
        title: "Apps & Resources",
        items: [
          { name: "Free Kindle Reading Apps", link: "#" },
          { name: "Kindle Cloud Reader", link: "#" },
          { name: "Manage Your Content and Devices", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Digital Content & Devices",
    name: "Appstore for Android",
    sections: [
      {
        title: "Appstore For Android",
        items: [
          { name: "All Apps and Games", link: "#" },
          { name: "Games", link: "#" },
          { name: "Amazon Coins", link: "#" },
          { name: "Download Amazon Appstore", link: "#" },
          { name: "Amazon Apps", link: "#" },
          { name: "Your Apps and Subscriptions", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Electronics",
    sections: [
      {
        title: "Electronics",
        items: [
          { name: "Accessories & Supplies", link: "#" },
          { name: "Camera & Photo", link: "#" },
          { name: "Car & Vehicle Electronics", link: "#" },
          { name: "Cell Phones & Accessories", link: "#" },
          { name: "Computers & Accessories", link: "#" },
          { name: "GPS & Navigation", link: "#" },
          { name: "Headphones", link: "#" },
          { name: "Home Audio", link: "#" },
          { name: "Office Electronics", link: "#" },
          { name: "Portable Audio & Video", link: "#" },
          { name: "Security & Surveillance", link: "#" },
          { name: "Service Plans", link: "#" },
          { name: "Television & Video", link: "#" },
          { name: "Video Game Consoles & Accessories", link: "#" },
          { name: "Video Projectors", link: "#" },
          { name: "Wearable Technology", link: "#" },
          { name: "eBook Readers & Accessories", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Computers",
    sections: [
      {
        title: "Computers",
        items: [
          { name: "Computer Accessories & Peripherals", link: "#" },
          { name: "Computer Components", link: "#" },
          { name: "Computers & Tablets", link: "#" },
          { name: "Data Storage", link: "#" },
          { name: "External Components", link: "#" },
          { name: "Laptop Accessories", link: "#" },
          { name: "Monitors", link: "#" },
          { name: "Networking Products", link: "#" },
          { name: "Power Strips & Surge Protectors", link: "#" },
          { name: "Printers", link: "#" },
          { name: "Scanners", link: "#" },
          { name: "Servers", link: "#" },
          { name: "Tablet Accessories", link: "#" },
          { name: "Tablet Replacement Parts", link: "#" },
          { name: "Warranties & Services", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Smart Home",
    sections: [
      {
        title: "Smart Home",
        items: [
          { name: "Amazon Smart Home", link: "#" },
          { name: "Smart Home Lighting", link: "#" },
          { name: "Smart Locks and Entry", link: "#" },
          { name: "Security Cameras and Systems", link: "#" },
          { name: "Plugs and Outlets", link: "#" },
          { name: "New Smart Devices", link: "#" },
          { name: "Heating and Cooling", link: "#" },
          { name: "Detectors and Sensors", link: "#" },
          { name: "Home Entertainment", link: "#" },
          { name: "Pet", link: "#" },
          { name: "Voice Assistants and Hubs", link: "#" },
          { name: "Kitchen", link: "#" },
          { name: "Vacuums and Mops", link: "#" },
          { name: "Lawn and Garden", link: "#" },
          { name: "WIFI and Networking", link: "#" },
          { name: "Other Solutions", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Arts & Crafts",
    sections: [
      {
        title: "Arts & Crafts",
        items: [
          { name: "Painting, Drawing & Art Supplies", link: "#" },
          { name: "Beading & Jewelry Making", link: "#" },
          { name: "Crafting", link: "#" },
          { name: "Fabric", link: "#" },
          { name: "Fabric Decorating", link: "#" },
          { name: "Knitting & Crochet", link: "#" },
          { name: "Needlework", link: "#" },
          { name: "Organization, Storage & Transport", link: "#" },
          { name: "Printmaking", link: "#" },
          { name: "Scrapbooking & Stamping", link: "#" },
          { name: "Sewing", link: "#" },
          { name: "Party Decorations & Supplies", link: "#" },
          { name: "Gift Wrapping Supplies", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Automotive",
    sections: [
      {
        title: "Automotive",
        items: [
          { name: "Car Care", link: "#" },
          { name: "Car Electronics & Accessories", link: "#" },
          { name: "Exterior Accessories", link: "#" },
          { name: "Interior Accessories", link: "#" },
          { name: "Lights & Lighting Accessories", link: "#" },
          { name: "Motorcycle & Powersports", link: "#" },
          { name: "Oils & Fluids", link: "#" },
          { name: "Paint & Paint Supplies", link: "#" },
          { name: "Performance Parts & Accessories", link: "#" },
          { name: "Replacement Parts", link: "#" },
          { name: "RV Parts & Accessories", link: "#" },
          { name: "Tires & Wheels", link: "#" },
          { name: "Tools & Equipment", link: "#" },
          { name: "Automotive Enthusiast Merchandise", link: "#" },
          { name: "Heavy Duty & Commercial Vehicle Equipment", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Baby",
    sections: [
      {
        title: "Baby",
        items: [
          { name: "Activity & Entertainment", link: "#" },
          { name: "Apparel & Accessories", link: "#" },
          { name: "Baby & Toddler Toys", link: "#" },
          { name: "Baby Care", link: "#" },
          { name: "Baby Stationery", link: "#" },
          { name: "Car Seats & Accessories", link: "#" },
          { name: "Diapering", link: "#" },
          { name: "Feeding", link: "#" },
          { name: "Gifts", link: "#" },
          { name: "Nursery", link: "#" },
          { name: "Potty Training", link: "#" },
          { name: "Pregnancy & Maternity", link: "#" },
          { name: "Safety", link: "#" },
          { name: "Strollers & Accessories", link: "#" },
          { name: "Travel Gear", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Beauty and personal care",
    sections: [
      {
        title: "Beauty And Personal Care",
        items: [
          { name: "Makeup", link: "#" },
          { name: "Skin Care", link: "#" },
          { name: "Hair Care", link: "#" },
          { name: "Fragrance", link: "#" },
          { name: "Foot, Hand & Nail Care", link: "#" },
          { name: "Tools & Accessories", link: "#" },
          { name: "Shave & Hair Removal", link: "#" },
          { name: "Personal Care", link: "#" },
          { name: "Oral Care", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Women's Fashion",
    sections: [
      {
        title: "Women's Fashion",
        items: [
          { name: "Clothing", link: "#" },
          { name: "Shoes", link: "#" },
          { name: "Jewelry", link: "#" },
          { name: "Watches", link: "#" },
          { name: "Handbags", link: "#" },
          { name: "Accessories", link: "#" },
          { name: "Men's Fashion", link: "#" },
          { name: "Girls' Fashion", link: "#" },
          { name: "Boys' Fashion", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Men's Fashion",
    sections: [
      {
        title: "Men's Fashion",
        items: [
          { name: "Clothing", link: "#" },
          { name: "Shoes", link: "#" },
          { name: "Watches", link: "#" },
          { name: "Accessories", link: "#" },
          { name: "Women's Fashion", link: "#" },
          { name: "Girls' Fashion", link: "#" },
          { name: "Boys' Fashion", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Girls' Fashion",
    sections: [
      {
        title: "Girls' Fashion",
        items: [
          { name: "Clothing", link: "#" },
          { name: "Shoes", link: "#" },
          { name: "Jewelry", link: "#" },
          { name: "Watches", link: "#" },
          { name: "Accessories", link: "#" },
          { name: "School Uniforms", link: "#" },
          { name: "Men's Fashion", link: "#" },
          { name: "Women's Fashion", link: "#" },
          { name: "Boys' Fashion", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Boys' Fashion",
    sections: [
      {
        title: "Boys' Fashion",
        items: [
          { name: "Clothing", link: "#" },
          { name: "Shoes", link: "#" },
          { name: "Jewelry", link: "#" },
          { name: "Watches", link: "#" },
          { name: "Accessories", link: "#" },
          { name: "School Uniforms", link: "#" },
          { name: "Men's Fashion", link: "#" },
          { name: "Women's Fashion", link: "#" },
          { name: "Girls' Fashion", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Health and Household",
    sections: [
      {
        title: "Health And Household",
        items: [
          { name: "Baby & Child Care", link: "#" },
          { name: "Health Care", link: "#" },
          { name: "Household Supplies", link: "#" },
          { name: "Medical Supplies & Equipment", link: "#" },
          { name: "Oral Care", link: "#" },
          { name: "Personal Care", link: "#" },
          { name: "Sexual Wellness", link: "#" },
          { name: "Sports Nutrition", link: "#" },
          { name: "Stationery & Gift Wrapping Supplies", link: "#" },
          { name: "Vision Care", link: "#" },
          { name: "Vitamins & Dietary Supplements", link: "#" },
          { name: "Wellness & Relaxation", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Home and Kitchen",
    sections: [
      {
        title: "Home And Kitchen",
        items: [
          { name: "Kids' Home Store", link: "#" },
          { name: "Kitchen & Dining", link: "#" },
          { name: "Bedding", link: "#" },
          { name: "Bath", link: "#" },
          { name: "Furniture", link: "#" },
          { name: "Home Décor", link: "#" },
          { name: "Wall Art", link: "#" },
          { name: "Lighting & Ceiling Fans", link: "#" },
          { name: "Seasonal Décor", link: "#" },
          { name: "Event & Party Supplies", link: "#" },
          { name: "Heating, Cooling & Air Quality", link: "#" },
          { name: "Irons & Steamers", link: "#" },
          { name: "Vacuums & Floor Care", link: "#" },
          { name: "Storage & Organization", link: "#" },
          { name: "Cleaning Supplies", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Industrial and Scientific",
    sections: [
      {
        title: "Industrial And Scientific",
        items: [
          { name: "Abrasive & Finishing Products", link: "#" },
          { name: "Additive Manufacturing Products", link: "#" },
          { name: "Commercial Door Products", link: "#" },
          { name: "Cutting Tools", link: "#" },
          { name: "Fasteners", link: "#" },
          { name: "Filtration", link: "#" },
          { name: "Food Service Equipment & Supplies", link: "#" },
          { name: "Hydraulics, Pneumatics & Plumbing", link: "#" },
          { name: "Industrial Electrical", link: "#" },
          { name: "Industrial Hardware", link: "#" },
          { name: "Industrial Power & Hand Tools", link: "#" },
          { name: "Janitorial & Sanitation Supplies", link: "#" },
          { name: "Lab & Scientific Products", link: "#" },
          { name: "Material Handling Products", link: "#" },
          { name: "Occupational Health & Safety Products", link: "#" },
          { name: "Power Transmission Products", link: "#" },
          { name: "Professional Dental Supplies", link: "#" },
          { name: "Professional Medical Supplies", link: "#" },
          { name: "Raw Materials", link: "#" },
          { name: "Retail Store Fixtures & Equipment", link: "#" },
          { name: "Robotics", link: "#" },
          { name: "Science Education", link: "#" },
          { name: "Tapes, Adhesives & Sealants", link: "#" },
          { name: "Test, Measure & Inspect", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Luggage",
    sections: [
      {
        title: "Luggage",
        items: [
          { name: "Carry-ons", link: "#" },
          { name: "Backpacks", link: "#" },
          { name: "Garment bags", link: "#" },
          { name: "Travel Totes", link: "#" },
          { name: "Luggage Sets", link: "#" },
          { name: "Laptop Bags", link: "#" },
          { name: "Suitcases", link: "#" },
          { name: "Kids Luggage", link: "#" },
          { name: "Messenger Bags", link: "#" },
          { name: "Umbrellas", link: "#" },
          { name: "Duffles", link: "#" },
          { name: "Travel Accessories", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Movies & Television",
    sections: [
      {
        title: "Movies & Television",
        items: [
          { name: "Movies", link: "#" },
          { name: "TV Shows", link: "#" },
          { name: "Blu-ray", link: "#" },
          { name: "4K Ultra HD", link: "#" },
          { name: "Best Sellers", link: "#" },
          { name: "Today's Deals", link: "#" },
          { name: "New Releases", link: "#" },
          { name: "Pre-orders", link: "#" },
          { name: "Kids & Family", link: "#" },
          { name: "Prime Video", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Pet supplies",
    sections: [
      {
        title: "Pet Supplies",
        items: [
          { name: "Dogs", link: "#" },
          { name: "Cats", link: "#" },
          { name: "Fish & Aquatic Pets", link: "#" },
          { name: "Birds", link: "#" },
          { name: "Horses", link: "#" },
          { name: "Reptiles & Amphibians", link: "#" },
          { name: "Small Animals", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Software",
    sections: [
      {
        title: "Software",
        items: [
          { name: "Accounting & Finance", link: "#" },
          { name: "Antivirus & Security", link: "#" },
          { name: "Business & Office", link: "#" },
          { name: "Children's", link: "#" },
          { name: "Design & Illustration", link: "#" },
          { name: "Digital Software", link: "#" },
          { name: "Education & Reference", link: "#" },
          { name: "Games", link: "#" },
          { name: "Lifestyle & Hobbies", link: "#" },
          { name: "Music", link: "#" },
          { name: "Networking & Servers", link: "#" },
          { name: "Operating Systems", link: "#" },
          { name: "Photography", link: "#" },
          { name: "Programming & Web Development", link: "#" },
          { name: "Tax Preparation", link: "#" },
          { name: "Utilities", link: "#" },
          { name: "Video", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Sports and Outdoors",
    sections: [
      {
        title: "Sports And Outdoors",
        items: [
          { name: "Sports and Outdoors", link: "#" },
          { name: "Outdoor Recreation", link: "#" },
          { name: "Sports & Fitness", link: "#" },
          { name: "Fan Shop", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Tools & Home Improvement",
    sections: [
      {
        title: "Tools & Home Improvement",
        items: [
          { name: "Tools & Home Improvement", link: "#" },
          { name: "Appliances", link: "#" },
          { name: "Building Supplies", link: "#" },
          { name: "Electrical", link: "#" },
          { name: "Hardware", link: "#" },
          { name: "Kitchen & Bath Fixtures", link: "#" },
          { name: "Light Bulbs", link: "#" },
          { name: "Lighting & Ceiling Fans", link: "#" },
          { name: "Measuring & Layout Tools", link: "#" },
          { name: "Painting Supplies & Wall Treatments", link: "#" },
          { name: "Power & Hand Tools", link: "#" },
          { name: "Rough Plumbing", link: "#" },
          { name: "Safety & Security", link: "#" },
          { name: "Storage & Home Organization", link: "#" },
          { name: "Welding & Soldering", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Toys and Games",
    sections: [
      {
        title: "Toys And Games",
        items: [
          { name: "Action Figures & Statues", link: "#" },
          { name: "Arts & Crafts", link: "#" },
          { name: "Baby & Toddler Toys", link: "#" },
          { name: "Building Toys", link: "#" },
          { name: "Dolls & Accessories", link: "#" },
          { name: "Dress Up & Pretend Play", link: "#" },
          { name: "Kids' Electronics", link: "#" },
          { name: "Games", link: "#" },
          { name: "Grown-Up Toys", link: "#" },
          { name: "Hobbies", link: "#" },
          { name: "Kids' Furniture, Décor & Storage", link: "#" },
          { name: "Learning & Education", link: "#" },
          { name: "Novelty & Gag Toys", link: "#" },
          { name: "Party Supplies", link: "#" },
          { name: "Puppets", link: "#" },
          { name: "Puzzles", link: "#" },
          { name: "Sports & Outdoor Play", link: "#" },
          { name: "Stuffed Animals & Plush Toys", link: "#" },
          { name: "Toy Remote Control & Play Vehicles", link: "#" },
          { name: "Tricycles, Scooters & Wagons", link: "#" },
          { name: "Video Games", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Shop By Department",
    name: "Video Games",
    sections: [
      {
        title: "Video Games",
        items: [
          { name: "Video Games", link: "#" },
          { name: "PlayStation 4", link: "#" },
          { name: "PlayStation 3", link: "#" },
          { name: "Xbox One", link: "#" },
          { name: "Xbox 360", link: "#" },
          { name: "Nintendo Switch", link: "#" },
          { name: "Wii U", link: "#" },
          { name: "Wii", link: "#" },
          { name: "PC", link: "#" },
          { name: "Mac", link: "#" },
          { name: "Nintendo 3DS & 2DS", link: "#" },
          { name: "Nintendo DS", link: "#" },
          { name: "PlayStation Vita", link: "#" },
          { name: "Sony PSP", link: "#" },
          { name: "Retro Gaming & Microconsoles", link: "#" },
          { name: "Accessories", link: "#" },
          { name: "Digital Games", link: "#" },
          { name: "Kids & Family", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Programs & Features",
    name: "Gift Cards",
    sections: [
      {
        title: "Give A Gift Card",
        items: [
          { name: "All gift cards", link: "#" },
          { name: "eGift cards", link: "#" },
          { name: "Gift cards by mail", link: "#" },
          { name: "Specialty gift cards", link: "#" },
          { name: "Amazon Cash", link: "#" },
          { name: "For Businesses", link: "#" },
        ],
      },
      {
        title: "Manage Your Gift Card",
        items: [
          { name: "Redeem a gift card", link: "#" },
          { name: "View Your Balance", link: "#" },
          { name: "Reload Your Balance", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Programs & Features",
    name: "Amazon Live",
    sections: [
      {
        title: "Amazon Live",
        items: [
          { name: "Live", link: "#" },
          { name: "Recently Live", link: "#" },
        ],
      },
    ],
  },
  {
    header: "Programs & Features",
    name: "International Shopping",
    sections: [
      {
        title: "International Shopping",
        items: [
          { name: "Where we ship", link: "#" },
          { name: "Visit Amazon Global", link: "#" },
        ],
      },
    ],
  },
];

export default subMenus;
